<?php
/**
 * Sales Tracker API
 * -----------------
 * Tracks app sales generated by support/sales team members.
 *
 * Endpoints (single file, routed by method + `action`):
 *   GET   ?action=list              List records (supports search & filtering)
 *   GET   ?action=meta              Distinct salespeople & apps present in data
 *   POST  {action:'create', ...}    Create a record
 *   POST  {action:'update', id,...} Update a record
 *   POST  {action:'delete', id}     Delete a record
 *
 * The `sales_records` table is created automatically on first use.
 */

require_once __DIR__ . '/../config/cors.php';
require_once __DIR__ . '/../config/database.php';

/**
 * Ensure the sales_records table exists (self-bootstrapping).
 */
function ensureSalesTable(PDO $conn): void {
    $conn->exec("
        CREATE TABLE IF NOT EXISTS sales_records (
            id INT AUTO_INCREMENT PRIMARY KEY,
            store_name     VARCHAR(255) NOT NULL,
            store_link     VARCHAR(500) NULL,
            customer_email VARCHAR(255) NULL,
            app_name       VARCHAR(255) NOT NULL,
            salesperson    VARCHAR(255) NOT NULL,
            sale_date      DATE NOT NULL,
            created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_app (app_name),
            INDEX idx_salesperson (salesperson),
            INDEX idx_sale_date (sale_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    ");

    // Migration: rename the legacy customer_name column to customer_email,
    // preserving any existing data. Idempotent — runs only once.
    $hasOld = $conn->query("SHOW COLUMNS FROM sales_records LIKE 'customer_name'")->fetch();
    $hasNew = $conn->query("SHOW COLUMNS FROM sales_records LIKE 'customer_email'")->fetch();
    if ($hasOld && !$hasNew) {
        $conn->exec("ALTER TABLE sales_records CHANGE customer_name customer_email VARCHAR(255) NULL");
    }
}

/** Read a JSON body for POST requests, falling back to form-encoded $_POST. */
function readBody(): array {
    $raw = file_get_contents('php://input');
    if ($raw) {
        $json = json_decode($raw, true);
        if (is_array($json)) return $json;
    }
    return $_POST ?: [];
}

/** Send a JSON response and exit. */
function respond($payload, int $code = 200): void {
    http_response_code($code);
    echo json_encode($payload);
    exit;
}

/** Trim + strip tags to keep stored values clean. */
function clean($value): string {
    return trim(strip_tags((string) $value));
}

try {
    $database = new Database();
    $conn = $database->getConnection();
    if (!$conn) {
        respond(['success' => false, 'error' => 'Database connection failed'], 500);
    }
    ensureSalesTable($conn);

    $method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
    $body   = ($method === 'POST') ? readBody() : [];
    $action = $_GET['action'] ?? $body['action'] ?? ($method === 'GET' ? 'list' : '');

    switch ($action) {

        // ---- List with search & filtering -------------------------------
        case 'list': {
            $where  = [];
            $params = [];

            $search      = clean($_GET['search'] ?? '');
            $salesperson = clean($_GET['salesperson'] ?? '');
            $appName     = clean($_GET['app_name'] ?? '');
            $startDate   = clean($_GET['start_date'] ?? '');
            $endDate     = clean($_GET['end_date'] ?? '');

            if ($search !== '') {
                // Native prepares disallow reusing one placeholder, so bind per-column.
                $where[] = '(store_name LIKE :s1 OR store_link LIKE :s2
                             OR customer_email LIKE :s3 OR app_name LIKE :s4
                             OR salesperson LIKE :s5)';
                $like = '%' . $search . '%';
                $params[':s1'] = $like;
                $params[':s2'] = $like;
                $params[':s3'] = $like;
                $params[':s4'] = $like;
                $params[':s5'] = $like;
            }
            if ($salesperson !== '') {
                $where[] = 'salesperson = :salesperson';
                $params[':salesperson'] = $salesperson;
            }
            if ($appName !== '') {
                $where[] = 'app_name = :app_name';
                $params[':app_name'] = $appName;
            }
            if ($startDate !== '') {
                $where[] = 'sale_date >= :start_date';
                $params[':start_date'] = $startDate;
            }
            if ($endDate !== '') {
                $where[] = 'sale_date <= :end_date';
                $params[':end_date'] = $endDate;
            }

            $sql = 'SELECT id, store_name, store_link, customer_email, app_name,
                           salesperson, sale_date, created_at, updated_at
                    FROM sales_records';
            if ($where) {
                $sql .= ' WHERE ' . implode(' AND ', $where);
            }
            $sql .= ' ORDER BY sale_date DESC, id DESC';

            $stmt = $conn->prepare($sql);
            $stmt->execute($params);
            $records = $stmt->fetchAll(PDO::FETCH_ASSOC);

            respond([
                'success' => true,
                'count'   => count($records),
                'records' => $records,
            ]);
        }

        // ---- Distinct values for filter dropdowns -----------------------
        case 'meta': {
            $salespeople = $conn->query(
                "SELECT DISTINCT salesperson FROM sales_records
                 WHERE salesperson <> '' ORDER BY salesperson"
            )->fetchAll(PDO::FETCH_COLUMN);
            $apps = $conn->query(
                "SELECT DISTINCT app_name FROM sales_records
                 WHERE app_name <> '' ORDER BY app_name"
            )->fetchAll(PDO::FETCH_COLUMN);

            respond([
                'success'     => true,
                'salespeople' => $salespeople,
                'apps'        => $apps,
            ]);
        }

        // ---- Create -----------------------------------------------------
        case 'create': {
            $storeName   = clean($body['store_name'] ?? '');
            $storeLink   = clean($body['store_link'] ?? '');
            $customer    = clean($body['customer_email'] ?? '');
            $appName     = clean($body['app_name'] ?? '');
            $salesperson = clean($body['salesperson'] ?? '');
            $saleDate    = clean($body['sale_date'] ?? '');

            if ($storeName === '' && $storeLink === '') {
                respond(['success' => false, 'error' => 'Store name or store link is required'], 422);
            }
            if ($customer !== '' && !filter_var($customer, FILTER_VALIDATE_EMAIL)) {
                respond(['success' => false, 'error' => 'Customer mail ID must be a valid email'], 422);
            }
            if ($appName === '')     respond(['success' => false, 'error' => 'App name is required'], 422);
            if ($salesperson === '') respond(['success' => false, 'error' => 'Salesperson is required'], 422);
            if ($saleDate === '')    respond(['success' => false, 'error' => 'Sale date is required'], 422);

            // Allow store link to stand in for store name if name omitted.
            if ($storeName === '') $storeName = $storeLink;

            $stmt = $conn->prepare(
                'INSERT INTO sales_records
                    (store_name, store_link, customer_email, app_name, salesperson, sale_date)
                 VALUES (:store_name, :store_link, :customer_email, :app_name, :salesperson, :sale_date)'
            );
            $stmt->execute([
                ':store_name'     => $storeName,
                ':store_link'     => $storeLink !== '' ? $storeLink : null,
                ':customer_email' => $customer !== '' ? $customer : null,
                ':app_name'       => $appName,
                ':salesperson'    => $salesperson,
                ':sale_date'      => $saleDate,
            ]);

            respond(['success' => true, 'id' => (int) $conn->lastInsertId()], 201);
        }

        // ---- Update -----------------------------------------------------
        case 'update': {
            $id = (int) ($body['id'] ?? 0);
            if ($id <= 0) respond(['success' => false, 'error' => 'Valid record id is required'], 422);

            $storeName   = clean($body['store_name'] ?? '');
            $storeLink   = clean($body['store_link'] ?? '');
            $customer    = clean($body['customer_email'] ?? '');
            $appName     = clean($body['app_name'] ?? '');
            $salesperson = clean($body['salesperson'] ?? '');
            $saleDate    = clean($body['sale_date'] ?? '');

            if ($storeName === '' && $storeLink === '') {
                respond(['success' => false, 'error' => 'Store name or store link is required'], 422);
            }
            if ($customer !== '' && !filter_var($customer, FILTER_VALIDATE_EMAIL)) {
                respond(['success' => false, 'error' => 'Customer mail ID must be a valid email'], 422);
            }
            if ($appName === '')     respond(['success' => false, 'error' => 'App name is required'], 422);
            if ($salesperson === '') respond(['success' => false, 'error' => 'Salesperson is required'], 422);
            if ($saleDate === '')    respond(['success' => false, 'error' => 'Sale date is required'], 422);

            if ($storeName === '') $storeName = $storeLink;

            $stmt = $conn->prepare(
                'UPDATE sales_records SET
                    store_name     = :store_name,
                    store_link     = :store_link,
                    customer_email = :customer_email,
                    app_name       = :app_name,
                    salesperson    = :salesperson,
                    sale_date      = :sale_date
                 WHERE id = :id'
            );
            $stmt->execute([
                ':store_name'     => $storeName,
                ':store_link'     => $storeLink !== '' ? $storeLink : null,
                ':customer_email' => $customer !== '' ? $customer : null,
                ':app_name'       => $appName,
                ':salesperson'   => $salesperson,
                ':sale_date'     => $saleDate,
                ':id'            => $id,
            ]);

            respond(['success' => true, 'updated' => $stmt->rowCount()]);
        }

        // ---- Delete -----------------------------------------------------
        case 'delete': {
            $id = (int) ($body['id'] ?? $_GET['id'] ?? 0);
            if ($id <= 0) respond(['success' => false, 'error' => 'Valid record id is required'], 422);

            $stmt = $conn->prepare('DELETE FROM sales_records WHERE id = :id');
            $stmt->execute([':id' => $id]);

            respond(['success' => true, 'deleted' => $stmt->rowCount()]);
        }

        // ---- Team performance aggregates --------------------------------
        case 'performance': {
            $salesperson = clean($_GET['salesperson'] ?? '');
            $month       = clean($_GET['month'] ?? '');        // YYYY-MM
            $startDate   = clean($_GET['start_date'] ?? '');
            $endDate     = clean($_GET['end_date'] ?? '');

            $where  = [];
            $params = [];

            if ($salesperson !== '') {
                $where[] = 'salesperson = :sp';
                $params[':sp'] = $salesperson;
            }
            // Month takes precedence over an explicit range.
            if ($month !== '') {
                $where[] = "DATE_FORMAT(sale_date, '%Y-%m') = :month";
                $params[':month'] = $month;
            } else {
                if ($startDate !== '') { $where[] = 'sale_date >= :sd'; $params[':sd'] = $startDate; }
                if ($endDate   !== '') { $where[] = 'sale_date <= :ed'; $params[':ed'] = $endDate; }
            }
            $whereSql = $where ? ('WHERE ' . implode(' AND ', $where)) : '';

            // Totals: apps sold (rows), unique stores, distinct apps covered.
            $stmt = $conn->prepare(
                "SELECT
                    COUNT(*)                     AS total_apps_sold,
                    COUNT(DISTINCT store_name)   AS total_unique_stores,
                    COUNT(DISTINCT app_name)     AS apps_covered
                 FROM sales_records $whereSql"
            );
            $stmt->execute($params);
            $totals = $stmt->fetch(PDO::FETCH_ASSOC) ?: [];

            // App-wise breakdown.
            $stmt = $conn->prepare(
                "SELECT app_name,
                        COUNT(*)                   AS count,
                        COUNT(DISTINCT store_name) AS unique_stores
                 FROM sales_records $whereSql
                 GROUP BY app_name
                 ORDER BY count DESC, app_name ASC"
            );
            $stmt->execute($params);
            $appBreakdown = $stmt->fetchAll(PDO::FETCH_ASSOC);

            // Daily summary.
            $stmt = $conn->prepare(
                "SELECT sale_date AS date, COUNT(*) AS count
                 FROM sales_records $whereSql
                 GROUP BY sale_date
                 ORDER BY sale_date ASC"
            );
            $stmt->execute($params);
            $daily = $stmt->fetchAll(PDO::FETCH_ASSOC);

            // Monthly summary.
            $stmt = $conn->prepare(
                "SELECT DATE_FORMAT(sale_date, '%Y-%m') AS month, COUNT(*) AS count
                 FROM sales_records $whereSql
                 GROUP BY month
                 ORDER BY month ASC"
            );
            $stmt->execute($params);
            $monthly = $stmt->fetchAll(PDO::FETCH_ASSOC);

            respond([
                'success' => true,
                'totals'  => [
                    'total_apps_sold'     => (int) ($totals['total_apps_sold'] ?? 0),
                    'total_unique_stores' => (int) ($totals['total_unique_stores'] ?? 0),
                    'apps_covered'        => (int) ($totals['apps_covered'] ?? 0),
                ],
                'app_breakdown'   => $appBreakdown,
                'daily_summary'   => $daily,
                'monthly_summary' => $monthly,
            ]);
        }

        // ---- App-wise performance report --------------------------------
        case 'app_report': {
            $appName = clean($_GET['app_name'] ?? '');
            if ($appName === '') {
                respond(['success' => false, 'error' => 'App name is required'], 422);
            }

            $range     = clean($_GET['range'] ?? 'last_30_days'); // last_30_days | custom
            $startDate = clean($_GET['start_date'] ?? '');
            $endDate   = clean($_GET['end_date'] ?? '');

            // Report scope: app + date range (independent of table search).
            $scopeWhere  = ['app_name = :app'];
            $scopeParams = [':app' => $appName];

            if ($range === 'custom' && ($startDate !== '' || $endDate !== '')) {
                if ($startDate !== '') { $scopeWhere[] = 'sale_date >= :sd'; $scopeParams[':sd'] = $startDate; }
                if ($endDate   !== '') { $scopeWhere[] = 'sale_date <= :ed'; $scopeParams[':ed'] = $endDate; }
            } else {
                // Default: last 30 days (inclusive of today).
                $scopeWhere[] = 'sale_date >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)';
            }
            $scopeSql = 'WHERE ' . implode(' AND ', $scopeWhere);

            // Summary cards.
            $stmt = $conn->prepare(
                "SELECT COUNT(*) AS total_sales, COUNT(DISTINCT store_name) AS unique_stores
                 FROM sales_records $scopeSql"
            );
            $stmt->execute($scopeParams);
            $summary = $stmt->fetch(PDO::FETCH_ASSOC) ?: [];

            // Ranking of support members for this app.
            $stmt = $conn->prepare(
                "SELECT salesperson,
                        COUNT(*)                   AS count,
                        COUNT(DISTINCT store_name) AS unique_stores
                 FROM sales_records $scopeSql
                 GROUP BY salesperson
                 ORDER BY count DESC, unique_stores DESC, salesperson ASC"
            );
            $stmt->execute($scopeParams);
            $ranking = $stmt->fetchAll(PDO::FETCH_ASSOC);

            // Records table: scope + optional search, sorted + paginated.
            $recWhere  = $scopeWhere;
            $recParams = $scopeParams;

            $search = clean($_GET['search'] ?? '');
            if ($search !== '') {
                $recWhere[] = '(store_name LIKE :q1 OR store_link LIKE :q2
                                OR salesperson LIKE :q3 OR customer_email LIKE :q4)';
                $like = '%' . $search . '%';
                $recParams[':q1'] = $like; $recParams[':q2'] = $like;
                $recParams[':q3'] = $like; $recParams[':q4'] = $like;
            }
            $recSql = 'WHERE ' . implode(' AND ', $recWhere);

            // Sorting (whitelisted columns only).
            $sortMap = [
                'sale_date'   => 'sale_date',
                'store_name'  => 'store_name',
                'salesperson' => 'salesperson',
            ];
            $sortBy = $sortMap[clean($_GET['sort'] ?? '')] ?? 'sale_date';
            $order  = strtolower(clean($_GET['order'] ?? 'desc')) === 'asc' ? 'ASC' : 'DESC';

            // Pagination (validated integers, safe to inline).
            $page  = max(1, (int) ($_GET['page'] ?? 1));
            $limit = min(100, max(1, (int) ($_GET['limit'] ?? 10)));
            $offset = ($page - 1) * $limit;

            // Total matching rows (for pagination).
            $stmt = $conn->prepare("SELECT COUNT(*) FROM sales_records $recSql");
            $stmt->execute($recParams);
            $total = (int) $stmt->fetchColumn();

            $stmt = $conn->prepare(
                "SELECT id, store_name, store_link, customer_email, salesperson, sale_date
                 FROM sales_records $recSql
                 ORDER BY $sortBy $order, id DESC
                 LIMIT $limit OFFSET $offset"
            );
            $stmt->execute($recParams);
            $items = $stmt->fetchAll(PDO::FETCH_ASSOC);

            respond([
                'success' => true,
                'summary' => [
                    'total_sales'   => (int) ($summary['total_sales'] ?? 0),
                    'unique_stores' => (int) ($summary['unique_stores'] ?? 0),
                ],
                'ranking' => $ranking,
                'records' => [
                    'items' => $items,
                    'total' => $total,
                    'page'  => $page,
                    'limit' => $limit,
                    'pages' => (int) ceil($total / $limit),
                ],
            ]);
        }

        default:
            respond(['success' => false, 'error' => "Unknown action: {$action}"], 400);
    }

} catch (PDOException $e) {
    respond(['success' => false, 'error' => 'Database error: ' . $e->getMessage()], 500);
} catch (Throwable $e) {
    respond(['success' => false, 'error' => 'Server error: ' . $e->getMessage()], 500);
}
